# Multi-stage docker file that
# first builds the war file using Gradle, and then
# deploys the built file to tomcat

FROM gradle:latest AS builder
LABEL maintainer="ramaswamy.ramanathan@anz.com"

WORKDIR /home/credible-eventsourcing
COPY *.gradle gradle.* gradlew ./
COPY gradle ./gradle
ENV GRADLE_OPTS  "-Xmx512m"
RUN ./gradlew --version

# Copy everything as we won't be keeping it anyway
COPY . .
RUN ./gradlew build --configure-on-demand

# Deploy war to Tomcat
# presumes that the war file has been generated locally.
FROM openjdk:11.0.4-jre-slim
ARG env=dev
LABEL maintainer="ramaswamy.ramanathan@anz.com"
EXPOSE 8085

ARG JAR_FILE=./build/libs/*.jar
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["sh", "-c", "java ${JAVA_OPTS} -jar /app.jar"]
